version: '0.1.0'
services:
  backend:
    image: myovision-backend:latest #
    ports:
      - "8080:8080"
    environment:
      - REDIS__HOST=redis
      - REDIS__PORT=6379
    depends_on:
      redis:
        condition: service_healthy
    env_file:
      - .env

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    command: redis-server
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
