version: '0.1.0'
services:
  backend:
    build:
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    environment:
      - MYOVISION_REDIS__HOST=redis
      - MYOVISION_REDIS__PORT=6379
    depends_on:
      redis:
        condition: service_healthy
    env_file:
      - .env
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    command: redis-server
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
