version: '0.1.0'
services:
  backend:
    image: myovision-backend:latest
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      redis:
        condition: service_healthy
    env_file:
      - .env

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    command: redis-server
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  frontend:
    image: myovision-frontend:latest
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    environment:
      - BACKEND_HOST=backend
    depends_on:
      - backend
    env_file:
      - .env
